# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\A DATA KULIAH\TA\Source Code\Mouse_PyQT\epm.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1031, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.gridWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridWidget.setGeometry(QtCore.QRect(690, 10, 313, 161))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridWidget.sizePolicy().hasHeightForWidth())
        self.gridWidget.setSizePolicy(sizePolicy)
        self.gridWidget.setObjectName("gridWidget")
        self.Result_Window = QtWidgets.QGridLayout(self.gridWidget)
        self.Result_Window.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.Result_Window.setContentsMargins(5, 5, 5, 5)
        self.Result_Window.setHorizontalSpacing(5)
        self.Result_Window.setObjectName("Result_Window")
        self.Result_RC = QtWidgets.QTextEdit(self.gridWidget)
        self.Result_RC.setReadOnly(True)
        self.Result_RC.setObjectName("Result_RC")
        self.Result_Window.addWidget(self.Result_RC, 3, 1, 1, 1)
        self.pushButton_R = QtWidgets.QPushButton(self.gridWidget)
        self.pushButton_R.setObjectName("pushButton_R")
        self.Result_Window.addWidget(self.pushButton_R, 3, 3, 1, 1)
        self.Result_RLabel = QtWidgets.QTextEdit(self.gridWidget)
        self.Result_RLabel.setReadOnly(True)
        self.Result_RLabel.setObjectName("Result_RLabel")
        self.Result_Window.addWidget(self.Result_RLabel, 0, 3, 1, 1)
        self.Result_LT = QtWidgets.QTextEdit(self.gridWidget)
        self.Result_LT.setReadOnly(True)
        self.Result_LT.setObjectName("Result_LT")
        self.Result_Window.addWidget(self.Result_LT, 2, 2, 1, 1)
        self.Result_RT = QtWidgets.QTextEdit(self.gridWidget)
        self.Result_RT.setReadOnly(True)
        self.Result_RT.setObjectName("Result_RT")
        self.Result_Window.addWidget(self.Result_RT, 3, 2, 1, 1)
        self.pushButton_L = QtWidgets.QPushButton(self.gridWidget)
        self.pushButton_L.setObjectName("pushButton_L")
        self.Result_Window.addWidget(self.pushButton_L, 2, 3, 1, 1)
        self.Result_LC = QtWidgets.QTextEdit(self.gridWidget)
        self.Result_LC.setReadOnly(True)
        self.Result_LC.setObjectName("Result_LC")
        self.Result_Window.addWidget(self.Result_LC, 2, 1, 1, 1)
        self.Result_TT = QtWidgets.QTextEdit(self.gridWidget)
        self.Result_TT.setReadOnly(True)
        self.Result_TT.setObjectName("Result_TT")
        self.Result_Window.addWidget(self.Result_TT, 5, 2, 1, 1)
        self.Result_TC = QtWidgets.QTextEdit(self.gridWidget)
        self.Result_TC.setReadOnly(True)
        self.Result_TC.setObjectName("Result_TC")
        self.Result_Window.addWidget(self.Result_TC, 5, 1, 1, 1)
        self.pushButton_T = QtWidgets.QPushButton(self.gridWidget)
        self.pushButton_T.setObjectName("pushButton_T")
        self.Result_Window.addWidget(self.pushButton_T, 5, 3, 1, 1)
        self.Result_PLabel = QtWidgets.QTextEdit(self.gridWidget)
        self.Result_PLabel.setEnabled(True)
        self.Result_PLabel.setReadOnly(True)
        self.Result_PLabel.setObjectName("Result_PLabel")
        self.Result_Window.addWidget(self.Result_PLabel, 0, 0, 1, 1)
        self.Result_L = QtWidgets.QTextEdit(self.gridWidget)
        self.Result_L.setReadOnly(True)
        self.Result_L.setObjectName("Result_L")
        self.Result_Window.addWidget(self.Result_L, 2, 0, 1, 1)
        self.Result_CLabel = QtWidgets.QTextEdit(self.gridWidget)
        self.Result_CLabel.setReadOnly(True)
        self.Result_CLabel.setObjectName("Result_CLabel")
        self.Result_Window.addWidget(self.Result_CLabel, 0, 1, 1, 1)
        self.Result_B = QtWidgets.QTextEdit(self.gridWidget)
        self.Result_B.setReadOnly(True)
        self.Result_B.setObjectName("Result_B")
        self.Result_Window.addWidget(self.Result_B, 6, 0, 1, 1)
        self.Result_BT = QtWidgets.QTextEdit(self.gridWidget)
        self.Result_BT.setReadOnly(True)
        self.Result_BT.setObjectName("Result_BT")
        self.Result_Window.addWidget(self.Result_BT, 6, 2, 1, 1)
        self.Result_BC = QtWidgets.QTextEdit(self.gridWidget)
        self.Result_BC.setReadOnly(True)
        self.Result_BC.setObjectName("Result_BC")
        self.Result_Window.addWidget(self.Result_BC, 6, 1, 1, 1)
        self.pushButton_B = QtWidgets.QPushButton(self.gridWidget)
        self.pushButton_B.setObjectName("pushButton_B")
        self.Result_Window.addWidget(self.pushButton_B, 6, 3, 1, 1)
        self.Result_R = QtWidgets.QTextEdit(self.gridWidget)
        self.Result_R.setReadOnly(True)
        self.Result_R.setObjectName("Result_R")
        self.Result_Window.addWidget(self.Result_R, 3, 0, 1, 1)
        self.Result_T = QtWidgets.QTextEdit(self.gridWidget)
        self.Result_T.setReadOnly(True)
        self.Result_T.setObjectName("Result_T")
        self.Result_Window.addWidget(self.Result_T, 5, 0, 1, 1)
        self.Result_TLabel = QtWidgets.QTextEdit(self.gridWidget)
        self.Result_TLabel.setReadOnly(True)
        self.Result_TLabel.setObjectName("Result_TLabel")
        self.Result_Window.addWidget(self.Result_TLabel, 0, 2, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(690, 180, 311, 169))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_select_video = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_select_video.setEnabled(False)
        self.pushButton_select_video.setObjectName("pushButton_select_video")
        self.gridLayout.addWidget(self.pushButton_select_video, 3, 0, 1, 1)
        self.comboBox_Camera = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_Camera.setObjectName("comboBox_Camera")
        self.comboBox_Camera.addItem("")
        self.comboBox_Camera.addItem("")
        self.comboBox_Camera.addItem("")
        self.gridLayout.addWidget(self.comboBox_Camera, 3, 1, 1, 1)
        self.pushButton_start = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_start.sizePolicy().hasHeightForWidth())
        self.pushButton_start.setSizePolicy(sizePolicy)
        self.pushButton_start.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton_start.setObjectName("pushButton_start")
        self.gridLayout.addWidget(self.pushButton_start, 6, 0, 1, 2)
        self.video_status = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video_status.sizePolicy().hasHeightForWidth())
        self.video_status.setSizePolicy(sizePolicy)
        self.video_status.setStyleSheet("background:rgb(200, 196, 190)")
        self.video_status.setObjectName("video_status")
        self.gridLayout.addWidget(self.video_status, 2, 0, 1, 2)
        self.Label_status = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.Label_status.setStyleSheet(" font-size: 16pt;\n"
"               font-weight: bold;\n"
"               color: white;\n"
"               background-color: #3B4252;\n"
"               border: 1px solid #4C566A;\n"
"               border-radius: 5px;\n"
"               padding: 5px;")
        self.Label_status.setObjectName("Label_status")
        self.gridLayout.addWidget(self.Label_status, 1, 0, 1, 1)
        self.timer_display = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.timer_display.setMinimumSize(QtCore.QSize(0, 40))
        self.timer_display.setStyleSheet("font-size: 18pt;\n"
"               font-weight: bold;\n"
"               color: white;\n"
"               background-color: #3B4252;\n"
"               border: 1px solid #4C566A;\n"
"               border-radius: 5px;")
        self.timer_display.setObjectName("timer_display")
        self.gridLayout.addWidget(self.timer_display, 1, 1, 1, 1)
        self.label_Frame1 = QtWidgets.QLabel(self.centralwidget)
        self.label_Frame1.setGeometry(QtCore.QRect(30, 10, 621, 551))
        self.label_Frame1.setStyleSheet("background:rgb(0, 0, 0)")
        self.label_Frame1.setText("")
        self.label_Frame1.setObjectName("label_Frame1")
        self.label_Frame2 = QtWidgets.QLabel(self.centralwidget)
        self.label_Frame2.setGeometry(QtCore.QRect(690, 370, 311, 201))
        self.label_Frame2.setStyleSheet("background:rgb(0, 0, 0)")
        self.label_Frame2.setText("")
        self.label_Frame2.setObjectName("label_Frame2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1031, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Result_RC.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>"))
        self.pushButton_R.setText(_translate("MainWindow", "Select"))
        self.Result_RLabel.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Region</p></body></html>"))
        self.Result_LT.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">00:00</p></body></html>"))
        self.Result_RT.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">00:00</p></body></html>"))
        self.pushButton_L.setText(_translate("MainWindow", "Select"))
        self.Result_LC.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>"))
        self.Result_TT.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">00:00</p></body></html>"))
        self.Result_TC.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>"))
        self.pushButton_T.setText(_translate("MainWindow", "Select"))
        self.Result_PLabel.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Position</p></body></html>"))
        self.Result_L.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Left - O</p></body></html>"))
        self.Result_CLabel.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Count</p></body></html>"))
        self.Result_B.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Bottom - C</p></body></html>"))
        self.Result_BT.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">00:00</p></body></html>"))
        self.Result_BC.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>"))
        self.pushButton_B.setText(_translate("MainWindow", "Select"))
        self.Result_R.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Right - O</p></body></html>"))
        self.Result_T.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Top - C</p></body></html>"))
        self.Result_TLabel.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Time</p></body></html>"))
        self.pushButton_select_video.setText(_translate("MainWindow", "Select Video"))
        self.comboBox_Camera.setItemText(0, _translate("MainWindow", "Camera 0"))
        self.comboBox_Camera.setItemText(1, _translate("MainWindow", "Camera 1"))
        self.comboBox_Camera.setItemText(2, _translate("MainWindow", "Camera 2"))
        self.pushButton_start.setText(_translate("MainWindow", "START"))
        self.video_status.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.Label_status.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">UNDEFINED</span></p></body></html>"))
        self.timer_display.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">05 : 00</span></p></body></html>"))
